Rest ap itask
MercantecData/serverside-programmering-littleyoru pull request #4
Opened 2019-11-28 08:46 UTC by littleyoru

Finished Rest API

2019-11-28 09:05 UTC, MadsBock requested changes
Før jeg kan teste dit program skal jeg kunne køre din SQL fil på min database. Det kan jeg ikke lige nu. Mangler der semi-kolons?

2019-11-28 11:02 UTC, littleyoru commented
Jeg har fikset det nu

2019-11-28 11:04 UTC, adamdanyx commented
Super, jeg kigger videre.

2019-11-28 11:07 UTC, adamdanyx commented
Du skal altså lige huske at teste dit SQL script før du pusher. Det virker stadigvæk ikke.

2019-11-28 12:06 UTC, MadsBock requested changes
- Lav en readme fil der forklarer hvordan man bruger din API
 - Din server vil crashe hvis du kalder res.Write() efter at du har kaldt res.End(). Dette må ikke kunne forekomme. Find en løsning.

2019-11-29 08:53 UTC, adamdanyx commented
Så virker det! Godt arbejde.

2019-11-29 08:53 UTC, closed without merging